# Generated by Django 4.0.3 on 2023-05-17 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_is_agent_user_is_branch_user_is_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='createdby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='modifiedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
