# Generated by Django 4.0.4 on 2023-07-08 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0031_customer_complexion'),
        ('Users', '0003_alter_user_createdby_alter_user_modifiedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='Masters.country'),
        ),
    ]
