# Generated by Django 3.2 on 2023-01-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField(blank=True, choices=[(1, 'Create'), (2, 'Update'), (3, 'Delete')], default=1, null=True)),
                ('tablename', models.CharField(blank=True, max_length=100, null=True)),
                ('recordcode', models.CharField(blank=True, max_length=50, null=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.SmallIntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('errorcode', models.CharField(blank=True, max_length=50, null=True)),
                ('requestbody', models.TextField(blank=True, null=True)),
                ('responsecontent', models.TextField(blank=True, null=True)),
                ('error_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('formula', models.CharField(blank=True, max_length=200, null=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.SmallIntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormulaUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('formula_txt', models.CharField(blank=True, max_length=200, null=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormulaVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=0, max_length=30, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('status', models.SmallIntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.SmallIntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menuitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
                ('link', models.CharField(blank=True, max_length=50, null=True)),
                ('sequence', models.IntegerField(blank=True, default=100, null=True)),
                ('click', models.CharField(blank=True, max_length=50, null=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.SmallIntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
                ('ref', models.IntegerField(blank=True, default=0, null=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.SmallIntegerField(blank=True, choices=[(0, 'Unseen'), (1, 'Seen')], default=0, null=True)),
                ('seen_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.SmallIntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.SmallIntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_masters', 'Can View Masters'), ('view_trans_approvals', 'Can View Transaction Approvals'), ('view_import', 'Can View Import'), ('view_export', 'Can View Export '), ('view_report', 'Can View Reports ')),
            },
        ),
        migrations.CreateModel(
            name='Submenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sequence', models.IntegerField(blank=True, default=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
                ('click', models.CharField(blank=True, max_length=50, null=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.SmallIntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=15)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
