# Generated by Django 3.2 on 2023-01-27 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('System', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='createdby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='submenuscreated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submenu',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='submenus', to='System.menu'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='modifiedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='submenusupdated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submenu',
            name='submenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='submenus', to='System.submenu'),
        ),
        migrations.AddField(
            model_name='restore',
            name='createdby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='restorescreated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restore',
            name='modifiedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='restoresupdated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationusers',
            name='notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='notificationusers', to='System.notification'),
        ),
        migrations.AddField(
            model_name='notificationusers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='notificationusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='createdby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='menuitemscreated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='menuitems', to='System.menu'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='modifiedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='menuitemsupdated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='menuitems', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='submenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='menuitems', to='System.submenu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='createdby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='menuscreated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menu',
            name='modifiedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='menusupdated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formulavariables',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='formulavariables', to='System.formula'),
        ),
        migrations.AddField(
            model_name='formulaupdate',
            name='createdby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='formulaupdatescreated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formulaupdate',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='formulaupdates', to='System.formula'),
        ),
        migrations.AddField(
            model_name='formula',
            name='createdby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='formulascreated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formula',
            name='modifiedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='formulasupdated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backup',
            name='createdby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='backupscreated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backup',
            name='modifiedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='backupsupdated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='createdby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='attachmentscreated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='activitylogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
