# Generated by Django 3.2 on 2023-01-27 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='createdby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='statescreated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='state',
            name='modifiedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='statesupdated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='district',
            name='createdby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='districtscreated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='district',
            name='modifiedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='districtsupdated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='districts', to='Masters.state'),
        ),
        migrations.AddField(
            model_name='city',
            name='createdby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='citiescreated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cities', to='Masters.district'),
        ),
        migrations.AddField(
            model_name='city',
            name='modifiedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='citiesupdated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='areas', to='Masters.city'),
        ),
        migrations.AddField(
            model_name='area',
            name='createdby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='areascreated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='areas', to='Masters.district'),
        ),
        migrations.AddField(
            model_name='area',
            name='modifiedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='areasupdated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='areas', to='Masters.state'),
        ),
    ]
