# Generated by Django 4.0.3 on 2023-04-22 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0003_country_state_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='districts', to='Masters.country'),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='states', to='Masters.country'),
        ),
    ]
