# Generated by Django 4.0.3 on 2023-05-13 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Masters', '0013_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.SmallIntegerField(default=1, null=True)),
                ('createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='staffcreated', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='staffupdated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
