# Generated by Django 4.0.3 on 2023-05-14 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0015_rename_age_staff_branch_rename_name_staff_caste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='staff', to='Masters.branch'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='caste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='staff', to='Masters.caste'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='staff', to='Masters.religion'),
        ),
    ]
