# Generated by Django 4.0.3 on 2023-05-23 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Masters', '0017_branch_user_alter_staff_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('planname', models.CharField(blank=True, max_length=100, null=True)),
                ('plantype', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField(default=1, null=True)),
                ('contactsno', models.IntegerField(default=1, null=True)),
                ('amount', models.IntegerField(default=1, null=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('modifiedon', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.SmallIntegerField(default=1, null=True)),
                ('smsenable', models.SmallIntegerField(default=1, null=True)),
                ('emailenable', models.SmallIntegerField(default=1, null=True)),
                ('personalassistance', models.SmallIntegerField(default=1, null=True)),
                ('photozoom', models.SmallIntegerField(default=1, null=True)),
                ('sendinterest', models.SmallIntegerField(default=1, null=True)),
                ('profilesuggestions', models.SmallIntegerField(default=1, null=True)),
                ('createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='membershipcreated', to=settings.AUTH_USER_MODEL)),
                ('modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='membershipupdated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
