# Generated by Django 4.0.3 on 2023-05-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0018_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(default='no photo', upload_to='student_photos/'),
        ),
    ]
