# Generated by Django 4.0.4 on 2023-07-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0030_customer_aboutme_customer_age_customer_altemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='complexion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
