# Generated by Django 4.0.4 on 2023-07-22 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0039_customer_nameofappfilling_customer_nameofappmobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subcaste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='customer', to='Masters.subcaste'),
        ),
    ]
