# Generated by Django 4.0.4 on 2023-07-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0041_customer_eabroadaddress_customer_eabroadcountry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lookcaste',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='lookmaritalStatus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='lookprofession',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='leducation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
