# Generated by Django 4.0.4 on 2023-07-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0042_customer_lookcaste_customer_lookmaritalstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='leducation',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lookcaste',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lookmaritalStatus',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lookprofession',
            field=models.JSONField(default=dict),
        ),
    ]
