# Generated by Django 4.0.4 on 2023-07-30 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0046_visa'),
    ]

    operations = [
        migrations.AddField(
            model_name='caste',
            name='religion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='religions', to='Masters.religion'),
        ),
    ]
