# Generated by Django 4.0.4 on 2023-07-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0047_caste_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='abroadMobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='fatherAbroadMobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='motherAbroadMobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
