# Generated by Django 4.0.4 on 2023-07-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0051_alter_customer_eabroadvalidfrom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='stuabroadvalidfrom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='stuabroadvalidto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
