# Generated by Django 4.0.4 on 2023-08-16 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0052_alter_customer_stuabroadvalidfrom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='occupation', to='Masters.occupation'),
        ),
    ]
