# Generated by Django 4.0.4 on 2023-08-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0053_designation_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='interreligion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='lookdesignation',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthtime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
