# Generated by Django 4.0.4 on 2023-08-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0054_customer_interreligion_customer_lookdesignation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='eindiaworkingsince',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
