# Generated by Django 4.0.4 on 2023-08-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0055_alter_customer_eindiaworkingsince'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUserIds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
